import fs from 'fs';
const path = './config/company_boards.json';

const current = JSON.parse(fs.readFileSync(path, 'utf8'));
const moreCompanies = [
  "10xgenomics", "abnormal", "accel", "activecampaign", "adroll", "affine", "afterpay", "agora", "aircall", "algolia", "allbirds", "alteryx", 
  "amplitude", "anchor", "andela", "angellist", "anthropic", "apollo", "appcues", "appdynamics", "appfolio", "appian", "appsmith", "aptible", 
  "arduino", "articulate", "asana", "assembled", "astronomer", "atlassian", "attentive", "auth0", "authy", "automattic", "avant", "avito", 
  "axios", "bain", "bamboo", "bandcamp", "basecamp", "basis", "bazaarvoice", "bcg", "beepi", "belvedere", "benchling", "betaworks", "better", 
  "betterment", "bigcommerce", "bill", "bird", "bitly", "bitsight", "blackbaud", "blend", "blinkist", "block", "bloomberg", "bluecore", 
  "blueorigin", "boehringer", "bolt", "bombas", "bond", "booking", "box", "braintree", "branch", "braze", "breezy", "brex", "brilliant", 
  "buffer", "buildkite", "builtro", "bumble", "bureau", "buzzfeed", "bytedance", "c3", "cadence", "calm", "cameo", "canary", "canonical", 
  "canva", "capitalone", "capsule", "carmera", "carta", "carvana", "casper", "casetify", "castlight", "caterpillar", "caviar", "cbs", 
  "celonis", "celsius", "chainalysis", "chainlink", "check", "checkout", "checkr", "chegg", "chime", "chownow", "cisco", "citadel", 
  "citi", "cityblock", "clari", "classpass", "clear", "clearbit", "clever", "clickup", "cloudflare", "cloudkitchens", "clover", "coda", 
  "codecademy", "cognizant", "cohere", "coinbase", "collibra", "color", "comcast", "commure", "compass", "confluent", "consensys", "contentful", 
  "convoy", "core", "counsyl", "coursera", "covariant", "coveo", "creditkarma", "crossbeam", "crowdstrike", "cruise", "crunchbase", "criteo", 
  "cultureamp", "curative", "cvent", "cyberreason", "cypress", "daily", "dapperlabs", "darktrace", "dashlane", "databricks", "datacamp", 
  "datadog", "datarobot", "datastax", "dataiku", "deadlines", "deel", "deliveroo", "dell", "deloitte", "delta", "dentsu", "depop", 
  "descript", "dev", "dialpad", "didi", "digitalocean", "discord", "discover", "disney", "docker", "docusign", "doordash", "doximity", 
  "draftkings", "dribbble", "drift", "drizly", "dropbox", "duda", "duolingo", "dynatrace", "ea", "earnin", "ebay", "edmunds", "elastic", 
  "elevenlabs", "ellevest", "embark", "emburse", "emerson", "empower", "enigma", "enphase", "epic", "epicgames", "equifax", "ericsson", 
  "esri", "etsy", "eventbrite", "everlane", "evernote", "everside", "everyday", "evidation", "exabeam", "excel", "expedia", "expensify", 
  "experian", "extrahop", "fabric", "facebook", "faire", "fanatics", "fandango", "fannie", "farfetch", "farmers", "fast", "fastly", 
  "fathom", "fedex", "figma", "fincity", "fireblocks", "fireeye", "first", "fiserv", "fivetran", "flexport", "flipkart", "flow", 
  "fly", "flywire", "foodpanda", "ford", "fortinet", "forward", "foursquare", "fox", "framer", "freight", "freshworks", "front", 
  "ftx", "fullstory", "fundbox", "fundingcircle", "galaxy", "galileo", "gamedesires", "gameloft", "gap", "garmin", "gartner", "gatsby", 
  "ge", "geico", "gemini", "gene", "genesys", "genpact", "getaround", "getir", "getty", "github", "gitlab", "glassdoor", "glitch", 
  "global", "glossier", "glovo", "glu", "go", "gocardless", "godaddy", "gofundme", "gog", "gojek", "goldman", "gong", "goodrx", 
  "google", "gopuff", "gorillas", "goshen", "grab", "grafana", "graham", "grail", "grammarly", "greenhouse", "greylock", "grubhub", 
  "gucci", "guide", "guild", "gumroad", "guru", "gusto", "h1", "hackerone", "hashicorp", "hbo", "headspace", "health", "heap", 
  "hella", "hellofresh", "helpscout", "heroku", "hinge", "hios", "hippo", "hire", "hired", "hitachi", "home", "homedepot", "honda", 
  "honey", "honeybook", "hopper", "hostinger", "hotjar", "houzz", "hp", "hubspot", "hulu", "humana", "ibm", "icon", "idme", "ifood", 
  "illumina", "imgur", "improbable", "indeed", "index", "inmobi", "instabase", "instacart", "instart", "intel", "intercom", "intuit", 
  "invision", "invitae", "ion", "iron", "ironsource", "itau", "iterative", "jamf", "jasper", "jd", "jet", "jetbrains", "jll", 
  "jnj", "job", "jobot", "john", "jpmorgan", "jump", "juniper", "justeat", "kabam", "kabbage", "kaiser", "kantar", "karat", 
  "kayak", "keep", "kellogg", "kendra", "kenna", "kering", "key", "khan", "kickstarter", "kik", "k health", "king", "kite", 
  "klarna", "klaviyo", "kleiner", "koch", "konami", "kpmg", "kraft", "kraken", "kroger", "kuaishou", "kuka", "lendingclub", 
  "lendingtree", "lenovo", "lessonly", "level", "lever", "lexus", "lg", "lightspeed", "lime", "linear", "linkedin", "linktree", 
  "linode", "lionsgate", "liquid", "live", "liveramp", "livongo", "loco", "logitech", "logmein", "logrocket", "loom", "loreal", 
  "louis", "lucid", "lucidchart", "lula", "lumen", "luna", "lvmh", "lyft", "lyra", "mac", "macmillan", "macy", "magic", "magicleap", 
  "mailchimp", "main", "major", "maker", "mango", "map", "mapbox", "marathon", "marcus", "marigold", "marin", "marqeta", "marriott", 
  "mars", "marsh", "marvel", "masco", "mastercard", "masterclass", "match", "matrix", "mattel", "mattermost", "maven", "max", "maze", 
  "mcdonalds", "mckinsey", "medallia", "media", "medical", "medtronic", "meituan", "meltwater", "mercari", "merck", "mercury", "merge", 
  "meta", "metabase", "metlife", "metromile", "mews", "microsoft", "midjourney", "mindbody", "mint", "miro", "mixpanel", "mlb", "modern", 
  "modernhealth", "monday", "mongodb", "monster", "monzo", "moov", "morgan", "morningstar", "motional", "motorola", "mozilla", 
  "mparticle", "mrcooper", "msg", "mtv", "mulesoft", "mural", "mutiny", "mx", "myfitnesspal", "n26", "nab", "nasdaq", "nasa", 
  "national", "natwest", "nbc", "ncr", "ncsoft", "nec", "neo4j", "nerdwallet", "nest", "nestle", "netapp", "netease", "netflix", 
  "netlify", "netmarble", "netskope", "neuralink", "new", "newbalance", "newrelic", "news", "nexon", "next", "nextdoor", "nextroll", 
  "nexo", "niantic", "nike", "nintendo", "nissan", "nokia", "nomura", "noom", "nordstrom", "northern", "northrop", "norton", 
  "notion", "novartis", "novo", "nubank", "nuro", "nutanix", "nvidia", "nyt", "oak", "obsidian", "oculus", "offerup", "okcupid", 
  "okta", "ola", "olx", "omega", "omada", "omni", "on24", "one", "onemedical", "onfido", "open", "openai", "opendoor", "opensea", 
  "opensystems", "opera", "oppo", "optimizely", "optum", "oracle", "orange", "orbit", "orchard", "oscar", "outbrain", "outreach", 
  "over", "overstock", "oyo", "pac", "pacific", "pagerduty", "palantir", "palo", "panasonic", "panda", "pandora", "panera", 
  "papa", "papaya", "paramount", "parsley", "patagonia", "patch", "patreon", "paul", "paypal", "paystone", "paytm", "pbs", 
  "pci", "peacock", "pearlabyss", "pearson", "peloton", "pendo", "peng", "penn", "penske", "pepsi", "percy", "perfect", "perkin", 
  "perpay", "personal", "petco", "petsmart", "pfizer", "pg", "pgim", "philips", "philo", "phoenix", "photo", "pic", "pictet", 
  "pie", "pilot", "pinduoduo", "ping", "pinterest", "pioneer", "pipe", "piper", "pitch", "pitney", "pivot", "pixar", "pixel", 
  "plaid", "planet", "planetscale", "play", "playstation", "playtika", "plex", "plivo", "plume", "plus", "pnc", "point", 
  "pokemon", "polaris", "polaroid", "policy", "policygenius", "polygon", "polestar", "polo", "poly", "pomelo", "porsche", "port", 
  "post", "posthog", "postman", "postmates", "power", "practo", "prada", "prezi", "price", "priceline", "prime", "principal", 
  "procore", "procter", "productboard", "progress", "prologis", "proofpoint", "prosper", "proton", "prudential", "ps", "public", 
  "publicis", "pubmatic", "pulse", "puma", "puppet", "purdue", "pure", "pvh", "pwc", "qatar", "qcon", "qonto", "qualtrics", 
  "quantcast", "quantum", "quest", "quikr", "quill", "quora", "qurate", "qventus", "rabobank", "rackspace", "radar", "radiant", 
  "radius", "radnet", "railway", "rakuten", "rally", "ralph", "ramp", "randstad", "rapid7", "rappi", "raymond", "raytheon", 
  "razer", "rbc", "reach", "react", "read", "real", "realogy", "realtor", "reason", "rebag", "rebel", "recko", "red", "redbull", 
  "redfin", "redhat", "redis", "redox", "reebok", "reed", "regional", "regus", "reify", "reliant", "relx", "remark", "remedy", 
  "remitly", "remote", "renaissance", "renault", "render", "rent", "rental", "renttherunway", "republic", "resmed", "resolution", 
  "restaurant", "retail", "rethink", "retina", "retool", "reuters", "rev", "revolut", "rex", "reynolds", "rh", "rheinmetall", 
  "richemont", "ricoh", "rigup", "ring", "ringcentral", "riot", "rippling", "rite", "ritter", "rivian", "ro", "robert", "robinhood", 
  "roblox", "roche", "rock", "rocket", "rocketlawyer", "roku", "rolex", "roll", "rolls", "rooster", "root", "roper", "ross", 
  "rotary", "rover", "rovio", "royal", "rs", "rsm", "rubrik", "rudderstack", "run", "runkeeper", "runway", "rural", "rush", 
  "s&p", "saas", "sabre", "safari", "safe", "safeway", "sage", "sailpoint", "salesforce", "salesloft", "sally", "samsara", "samsung", 
  "sandia", "sandoz", "sanofi", "sanity", "santander", "sap", "sas", "samsung", "savills", "scale", "scaleai", "scania", "schneider", 
  "scholastic", "schroders", "schwab", "science", "scientific", "scopely", "scotiabank", "scott", "scout", "scribd", "scripps", "scythe", 
  "seagate", "sealed", "seamless", "sears", "seat", "seatgeek", "seattle", "securitas", "security", "sega", "segment", "seiko", "seismic", 
  "select", "self", "semrush", "sendbird", "sendgrid", "senior", "sense", "sentinelone", "sentry", "sephora", "sequoia", "sequoiacapital", 
  "servicenow", "sesame", "seven", "sezzle", "sg", "shake", "shangri", "sharp", "shaw", "shell", "sherwin", "shift", "shipt", 
  "shopify", "shutterfly", "shutterstock", "siemens", "sigma", "signify", "silver", "simon", "simple", "sinch", "singapore", 
  "sirius", "sisense", "sitecore", "sitel", "sittercity", "six", "sk", "skechers", "skillshare", "skillsoft", "skillz", 
  "skyscanner", "slack", "slalom", "slickdeals", "smart", "smartsheet", "smile", "smith", "smuckers", "snap", "snapchat", 
  "snowflake", "snyk", "sofi", "softbank", "software", "soho", "solar", "solarwinds", "solid", "solvay", "sompo", "sonos", 
  "sony", "sophos", "sorare", "sotheby", "sound", "soundcloud", "source", "south", "southwest", "space", "spacex", "spark", 
  "spectra", "spectrum", "speedway", "spin", "spire", "splashtop", "splunk", "sponsor", "sports", "spotify", "spredfast", 
  "spring", "springhealth", "sprint", "sproutfarmers", "sproutsocial", "spx", "square", "squareenix", "squarespace", "ssm", 
  "st", "standard", "stanford", "stanley", "star", "starbucks", "starling", "start", "starz", "stash", "state", "statefarm", 
  "steadily", "steel", "stealth", "stem", "step", "stepstone", "stifel", "stitch", "stitchfix", "stockx", "stone", "stop", 
  "storage", "strapi", "strat", "stratasys", "strategic", "strategy", "strava", "stream", "stride", "stripe", "stryker", 
  "stubhub", "studio", "stytch", "subaru", "subway", "success", "suez", "sumitomo", "summer", "sumo", "sun", "sunnova", 
  "sunpower", "sunrun", "super", "supercell", "superhuman", "supreme", "sure", "surface", "surveymonkey", "sushi", "susquehanna", 
  "suzuki", "sveriges", "swarovski", "swatch", "swedish", "sweet", "sweetgreen", "swiggy", "swiss", "swisscom", "swit", 
  "switch", "sykes", "symantec", "symphony", "sync", "synchrony", "syneos", "synopsys", "sysco", "system", "systems", "t-mobile", 
  "taboola", "taco", "takeda", "take-two", "tala", "talend", "talon", "tam", "tangerine", "tapestry", "target", "tata", 
  "tax", "taylor", "tbs", "tcf", "td", "teach", "team", "teams", "tech", "technical", "technicolor", "technology", 
  "techstars", "teck", "teg", "teksystems", "teladoc", "telecom", "telefonica", "telenor", "telstra", "telus", "temasek", 
  "tempus", "ten", "tenable", "tencent", "tenneco", "tential", "teradata", "teradyne", "terra", "tesla", "tether", "teva", 
  "texas", "text", "textron", "thales", "the", "theathletic", "theclorox", "thehartford", "theknot", "thermo", "thetradedesk", 
  "thewecompany", "think", "thomas", "thomson", "thought", "thoughtspot", "thoughtworks", "thrive", "thumbtack", "tiaa", 
  "ticketmaster", "tiktok", "tile", "timberland", "time", "tinder", "tipalti", "tire", "tjx", "tmobile", "toast", "today", 
  "tokyo", "toll", "tom", "tommy", "tomorrow", "toms", "top", "topcoder", "toptal", "toray", "torch", "toro", "toronto", 
  "toshiba", "total", "touch", "tower", "toyota", "tpg", "trace", "track", "tractor", "trade", "tradedesk", "tradeweb", 
  "traffic", "trail", "train", "trane", "trans", "transamerica", "transcarent", "transfer", "transferwise", "transition", 
  "transunion", "travel", "travelers", "travelex", "traveloka", "traverse", "treasury", "tree", "trell", "trellix", "trello", 
  "trend", "tri", "trimble", "trip", "tripactions", "tripadvisor", "tripping", "triton", "triumph", "trivago", "tron", 
  "true", "truecar", "truist", "trust", "trustpilot", "truth", "truveris", "tsmc", "tucows", "tui", "tuilio", "tupperware", 
  "turo", "tuttle", "tv", "tvs", "twilio", "twitch", "twitter", "two", "tyco", "tyler", "typeform", "tyson", "u-haul", 
  "uae", "uber", "ubereats", "ubisoft", "ubs", "ucb", "ucla", "udacity", "udemy", "ui", "uipath", "uk", "ukg", "ulta", 
  "ultimate", "ultra", "umb", "umi", "umpqua", "un", "under", "underarmour", "unicef", "unicredit", "unilever", "union", 
  "unique", "unisys", "united", "unitedhealth", "unity", "universal", "university", "univision", "uno", "unqork", "unsw", 
  "until", "up", "updox", "upfront", "uphold", "upmc", "ups", "upstart", "upwork", "urban", "urbn", "us", "usa", "usaa", 
  "usbank", "usda", "usd", "user", "usertesting", "usps", "ust", "utah", "utokyo", "vail", "valeo", "valero", "valley", 
  "valor", "value", "valve", "vancity", "vanguard", "vanilla", "vans", "var", "varonis", "vanguard", "varonis", "varta", 
  "vanguard", "vanguard", "varicent", "vast", "vatican", "vanguard", "vector", "veeam", "veeva", "velodyne", "vender", 
  "venafi", "venmo", "ventas", "venture", "veolia", "veracode", "veranda", "vercel", "verdict", "verily", "verisign", 
  "verisk", "veritas", "verizon", "verkada", "vertex", "vertical", "very", "verygoodsecurity", "vestas", "vet", "vf", 
  "via", "viacom", "viacomcbs", "viasat", "viber", "vice", "victoria", "vimeo", "vin", "vimeo", "virgin", "virginia", 
  "visa", "vision", "visit", "vista", "vistaprint", "visual", "vital", "vitamix", "vito", "vivo", "vmware", "vocal", 
  "vodafone", "voi", "voice", "volkswagen", "volvo", "vonage", "voodoo", "vornado", "vox", "voyager", "vroom", "vsco", 
  "vsp", "vtx", "vultr", "vw", "wabtec", "wade", "waffle", "wag", "walgreens", "walker", "wall", "walmart", "walt", 
  "wang", "warby", "warner", "warnerbros", "washington", "waste", "watch", "water", "watts", "wawa", "wayfair", "waymo", 
  "wayne", "wealth", "wealthfront", "wealthsimple", "wear", "weather", "web", "web3", "webflow", "webrtc", "website", 
  "webtrends", "wedding", "wedbush", "weedmaps", "weee", "weibo", "weight", "weir", "wellington", "wells", "wellsfargo", 
  "wendys", "wepay", "west", "western", "westfield", "westinghouse", "westmonroe", "westpac", "wework", "wex", "weyerhaeuser", 
  "whale", "wharton", "what", "whatsapp", "when", "where", "whirlpool", "white", "whole", "wieden", "williams", "willis", 
  "wilson", "wind", "window", "wipro", "wire", "wirecard", "wise", "wish", "wix", "wizards", "wmg", "wolf", "wolters", 
  "wolverine", "wood", "woodmac", "woolworths", "word", "work", "workato", "workday", "workfront", "workplace", "world", 
  "worldbank", "worldpay", "worldquant", "worldremit", "wp", "wpp", "wrike", "wunderkind", "wunderman", "wwe", "wyndham", 
  "wynn", "x", "xandr", "xbox", "xcel", "xendit", "xero", "xiaomi", "xilinx", "ximalaya", "xinity", "xo", "xometry", 
  "xpo", "xp", "y", "y-combinator", "yahoo", "yamaha", "yandex", "yardi", "yates", "y combinator", "ycombinator", "yellow", 
  "yelp", "yes", "yext", "yield", "ymca", "yoga", "yotpo", "you", "young", "your", "youtube", "yum", "yummly", "z", 
  "zain", "zalando", "zappos", "zara", "zebra", "zen", "zendesk", "zenefits", "zenga", "zenith", "zenoti", "zep", 
  "zero", "zeta", "zillow", "zimmer", "zimmerman", "zinder", "zip", "zipcar", "ziprecruiter", "zocdoc", "zoetis", 
  "zoh", "zoho", "zomato", "zone", "zoom", "zoominfo", "zoox", "zs", "zscaler", "zulily", "zurich", "zwift", "zynga"
];

const merged = Array.from(new Set([...current, ...moreCompanies]));
merged.sort();
fs.writeFileSync(path, JSON.stringify(merged, null, 2));
console.log(`Updated company_boards.json. Total companies: ${merged.length}`);
